# Generated by Django 2.2 on 2021-04-18 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Name', models.CharField(max_length=20)),
                ('P_Type', models.CharField(max_length=20)),
                ('P_NodeType', models.CharField(max_length=20)),
                ('P_Link', models.CharField(max_length=20)),
                ('P_DataFormat', models.CharField(max_length=20)),
                ('P_Authentication', models.CharField(max_length=20)),
                ('P_Describe', models.CharField(max_length=20)),
                ('P_ProductKey', models.CharField(max_length=20)),
                ('P_ProducSecret', models.CharField(max_length=20)),
                ('P_CreateData', models.DateTimeField(auto_now=True)),
                ('P_Status', models.CharField(max_length=5)),
                ('P_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_Info')),
            ],
        ),
    ]
