# Generated by Django 2.2 on 2021-04-18 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
        ('register', '0001_initial'),
        ('createproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_Name', models.CharField(max_length=20)),
                ('T_Dir', models.CharField(max_length=128)),
                ('T_Permission', models.CharField(max_length=5)),
                ('T_Data', models.CharField(max_length=20)),
                ('T_Device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.Device')),
                ('T_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createproduct.Product')),
                ('T_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_Info')),
            ],
        ),
    ]
