# Generated by Django 2.2 on 2021-04-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=18)),
                ('Password', models.CharField(max_length=64)),
                ('Tel', models.CharField(max_length=18)),
                ('Compant', models.CharField(max_length=30)),
                ('Other', models.CharField(max_length=300)),
                ('CreateData', models.DateTimeField(auto_now=True)),
                ('LoginData', models.DateTimeField(auto_now=True)),
                ('LoginIP', models.CharField(max_length=16)),
                ('RegisterIP', models.CharField(max_length=16)),
                ('ChecKey', models.CharField(max_length=32)),
            ],
        ),
    ]
