# Generated by Django 2.2 on 2021-04-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0001_initial'),
        ('createproduct', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Name', models.CharField(max_length=20)),
                ('D_Drscribe', models.CharField(max_length=100)),
                ('D_Stats', models.CharField(max_length=5)),
                ('D_LastTime', models.DateTimeField(auto_now=True)),
                ('D_Poduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createproduct.Product')),
                ('D_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.User_Info')),
            ],
        ),
    ]
